//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConcreteMediator : Mediator
{
	public virtual ConcreteColleague1 ConcreteColleague1
	{
		get;
		set;
	}

	public virtual ConcreteColleague2 ConcreteColleague2
	{
		get;
		set;
	}

}

